### ISSUE TITLE
CA store is obsolete

### ISSUE THREAD

**Issue by lfortemps** [MISP/cakephp#1]
The CA store in 
https://github.com/MISP/cakephp/tree/cf14e6546ec44e3369e3531add11fdb946656280/lib/Cake/Config

hasn't been updated for a while. We have noticed this is creating issue for sync between MISP servers if one of them is using Let's Encrypt certificates for which the previous root CA has expired 30 Sep 2021.

This is related to https://issueexplorer.com/issue/cakephp/cakephp/15987

Using curl with this ca store causes issues while using the OS store works fine. Following the solution described in the link above and using the new Mozilla CA store fixes the sync problem

**Comment by adulau** [comment]
I would propose to update the latest CA store of the newest version. @iglocska any objection ?

**Comment by adulau** [comment]
I propose to incorporate the following https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt - if there is no objection, I'll update it.

**Comment by adulau** [comment]
Fixed in c31bb4b4be00d2a0db22c9a038f9fad8a5950efe

**Comment by adulau** [comment]
@lfortemps it should be fixed. Feel free to reopen if you see any other issue. Thanks a lot!
